print("++++==Data diri mahasiswa==++++")
nim = input ("masukan nim: ")
nama = input ("masukan nama: ")
jurusan = input ("masukan jurusan: ")
alamat = input ("masukan alamat: ")
print ("--------------------------")
print ("hasil cetak data diatas adalah")
print ("nim : " +str(nim))
print ("nama :" +str(nama))
print ("jurusan :" +str(jurusan))
print ("alamat :" +str(alamat))